import {Dialog,DialogPanel,DialogTitle} from '@headlessui/react';
import {motion} from 'motion/react';
import {Activity,Bell,Boxes,CheckCircle2,ChevronRight,Droplets,Gauge,History,LogOut,Menu,Monitor,Save,ShieldCheck,Ship,Truck,Wrench,X} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {AuditPanel} from './components/AuditPanel';
import {Login} from './components/Login';
import {MaintenancePanel} from './components/MaintenancePanel';
import {OperationsPanel} from './components/OperationsPanel';
import {QhsePanel} from './components/QhsePanel';
import {TanksPanel} from './components/TanksPanel';
import {TrucksPanel} from './components/TrucksPanel';
import {TVPanel} from './components/TVPanel';
import {VesselsPanel} from './components/VesselsPanel';
import {advanceTruck,canWrite,createMaintenance,createOperation,createQhse,createTruck,loadAuditLogs,loadDashboard,loadEquipment,loadFluidTypes,loadProfile,loadTankHistory,updateOperation,updateTank,type AuditLog,type Equipment,type FluidType,type Maintenance,type Operation,type Profile,type QhseRecord,type Tank,type TankHistory,type Truck as TruckRecord,type VesselSchedule} from './lib/data';
import {supabase} from './lib/supabase';

const nav=[['Visão geral',Gauge],['Painel TV',Monitor],['Operações',Activity],['Tanques e silos',Droplets],['Embarcações',Ship],['Carretas',Truck],['Manutenção',Wrench],['QHSE',ShieldCheck],['Auditoria',History]] as const;
const demoTanks:Tank[]=[{id:'1',name:'TK-04',kind:'WBM',phase:'Phase #1',capacity:1000,current_volume:760,current_product:'KCL Polymer 9.8 ppg',status:'Operando',unit:'bbl',client:'Equinor',current_lot:'L-2407'}];

type FormKind='operation'|'truck'|'maintenance'|'qhse'|null;

function TankCard({tank,onOpen}:{tank:Tank;onOpen:(tank:Tank)=>void}){const pct=Math.min(100,Math.round(tank.current_volume/(tank.capacity||1)*100));return <motion.article whileHover={{y:-4}} className="tank-card"><div className="card-top"><div><span>{tank.kind}</span><h3>{tank.name}</h3></div><b>{tank.status}</b></div><div className="tank-visual"><motion.div className="liquid" animate={{height:`${pct}%`}}/><div className="tank-grid"/><strong>{pct}%</strong></div><div className="tank-copy"><h4>{tank.current_product||'Sem produto'}</h4><p>{tank.current_volume.toLocaleString('pt-BR')} / {tank.capacity.toLocaleString('pt-BR')} {tank.unit}</p><small>{tank.client||'Sem cliente'} · {tank.phase}</small></div><button onClick={()=>onOpen(tank)}>Ver detalhes <ChevronRight size={16}/></button></motion.article>}

function Dashboard({demo,onExitDemo}:{demo:boolean;onExitDemo:()=>void}){
 const[active,setActive]=useState('Visão geral'),[sidebar,setSidebar]=useState(false),[alertsOpen,setAlertsOpen]=useState(false),[selected,setSelected]=useState<Tank|null>(null),[editOpen,setEditOpen]=useState(false),[formOpen,setFormOpen]=useState<FormKind>(null),[editOperation,setEditOperation]=useState<Operation|null>(null);
 const[tanks,setTanks]=useState<Tank[]>(demo?demoTanks:[]),[operations,setOperations]=useState<Operation[]>([]),[vessels,setVessels]=useState<VesselSchedule[]>([]),[trucks,setTrucks]=useState<TruckRecord[]>([]),[maintenance,setMaintenance]=useState<Maintenance[]>([]),[qhse,setQhse]=useState<QhseRecord[]>([]),[alerts,setAlerts]=useState<any[]>([]),[summary,setSummary]=useState<any>(null),[history,setHistory]=useState<TankHistory[]>([]),[profile,setProfile]=useState<Profile|null>(null),[fluids,setFluids]=useState<FluidType[]>([]),[equipment,setEquipment]=useState<Equipment[]>([]),[audit,setAudit]=useState<AuditLog[]>([]),[notice,setNotice]=useState('');
 const[query,setQuery]=useState(''),[saving,setSaving]=useState(false);
 const[tankForm,setTankForm]=useState({volume:0,status:'Disponível',client:'',lot:'',fluid_type_id:''});
 const[operationForm,setOperationForm]=useState({vessel:'',client:'',product:'',activity:'Bombeio',planned_quantity:0,executed_quantity:0,unit:'bbl',scheduled_at:'',status:'Programada',notes:''});
 const[truckForm,setTruckForm]=useState({movement_date:new Date().toISOString().slice(0,10),movement_type:'Entrada',supplier:'',client:'',product:'',quantity:0,unit:'t',plate:'',driver_name:'',invoice_number:'',truck_type:'Bulk',notes:''});
 const[maintenanceForm,setMaintenanceForm]=useState({equipment_id:'',title:'',description:'',priority:'Média',maintenance_type:'Corretiva',responsible:'',due_date:''});
 const[qhseForm,setQhseForm]=useState({record_date:new Date().toISOString().slice(0,10),record_type:'Observação',title:'',description:'',responsible:'',severity:'Média'});
 async function refresh(){if(demo)return;const[d,a]=await Promise.all([loadDashboard(),loadAuditLogs()]);setTanks(d.tanks);setOperations(d.operations);setVessels(d.vessels);setTrucks(d.trucks);setMaintenance(d.maintenance);setQhse(d.qhse);setAlerts(d.alerts);setSummary(d.summary);setAudit(a)}
 useEffect(()=>{if(demo)return;Promise.all([refresh(),loadProfile().then(setProfile),loadFluidTypes().then(setFluids),loadEquipment().then(setEquipment)]).catch(e=>setNotice(e.message))},[demo]);
 useEffect(()=>{if(!selected)return;loadTankHistory(selected.id).then(setHistory).catch(()=>setHistory([]));setTankForm({volume:selected.current_volume,status:selected.status,client:selected.client||'',lot:selected.current_lot||'',fluid_type_id:selected.current_fluid_type_id||''})},[selected]);
 const filtered=useMemo(()=>tanks.filter(t=>`${t.name} ${t.current_product||''} ${t.client||''}`.toLowerCase().includes(query.toLowerCase())),[tanks,query]);
 const total=useMemo(()=>tanks.reduce((a,t)=>a+t.current_volume,0),[tanks]);
 const writeTanks=!demo&&canWrite(profile,'tanks'),writeOps=!demo&&canWrite(profile,'operations'),writeTrucks=!demo&&canWrite(profile,'trucks'),writeMaintenance=!demo&&canWrite(profile,'maintenance'),writeQhse=!demo&&canWrite(profile,'qhse');
 async function logout(){if(demo)onExitDemo();else await supabase?.auth.signOut()}
 async function act(fn:()=>Promise<unknown>,message:string){setSaving(true);setNotice('');try{await fn();await refresh();setFormOpen(null);setEditOperation(null);setNotice(message)}catch(e:any){setNotice(e.message||'Não foi possível concluir a ação.')}finally{setSaving(false)}}
 async function saveTank(){if(!selected)return;await act(()=>updateTank(selected,tankForm),'Tanque atualizado com sucesso.');setEditOpen(false);setSelected(null)}
 async function saveOperation(){if(editOperation)await act(()=>updateOperation(editOperation.id,operationForm),'Operação atualizada com sucesso.');else await act(()=>createOperation(operationForm),'Operação criada com sucesso.')}
 async function moveTruck(id:string,current:string|null){const stages=['programada','portaria','pátio','operação','liberada'];const next=stages[Math.min(stages.length-1,Math.max(0,stages.indexOf((current||'programada').toLowerCase())+1))];await act(()=>advanceTruck(id,next),`Carreta avançada para ${next}.`)}
 function openOperation(o?:Operation){if(o){setEditOperation(o);setOperationForm({vessel:o.vessel,client:o.client,product:o.product,activity:o.activity,planned_quantity:o.planned_quantity,executed_quantity:o.executed_quantity,unit:o.unit,scheduled_at:o.scheduled_at?.slice(0,16)||'',status:o.status,notes:o.notes||''})}else{setEditOperation(null);setOperationForm({vessel:'',client:'',product:'',activity:'Bombeio',planned_quantity:0,executed_quantity:0,unit:'bbl',scheduled_at:'',status:'Programada',notes:''})}setFormOpen('operation')}
 const metrics=[['Volume monitorado',`${total.toLocaleString('pt-BR')} un.`,Droplets],['Operações ativas',String(summary?.operations_in_progress??operations.length),Activity],['Carretas pendentes',String(summary?.trucks_pending??trucks.length),Truck],['Pendências QHSE',String(summary?.qhse_pending??qhse.filter(q=>q.status!=='Concluído').length),ShieldCheck]];
 return <div className="app-shell"><aside className={`sidebar ${sidebar?'open':''}`}><div className="brand"><div className="brand-mark"><Boxes/></div><div><strong>OPSControl</strong><span>IA NEXT</span></div><button onClick={()=>setSidebar(false)}><X/></button></div><div className="plant"><i/><div><span>{demo?'MODO HOMOLOGAÇÃO':'PLANTA ATIVA'}</span><strong>B-PORT LMP</strong></div></div><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?'active':''} onClick={()=>{setActive(label);setSidebar(false)}}><Icon size={18}/>{label}</button>)}</nav><button className="logout" onClick={logout}><LogOut size={18}/>Sair</button><div className="user"><div>{profile?.full_name?.slice(0,2).toUpperCase()||'OC'}</div><span><strong>{profile?.full_name||'Homologação visual'}</strong><small>{profile?.role||'Dados demonstrativos'}</small></span></div></aside>
 <main><header><button className="menu" onClick={()=>setSidebar(true)}><Menu/></button><div><span>Centro de controle operacional</span><h1>{active}</h1></div><button className="icon-button" onClick={()=>setAlertsOpen(true)}><Bell/><i>{alerts.length}</i></button></header>{notice&&<div className="notice"><CheckCircle2 size={18}/>{notice}<button onClick={()=>setNotice('')}><X size={15}/></button></div>}
 {active==='Visão geral'&&<><section className="hero"><div><span className="eyebrow">OPERAÇÃO EM TEMPO REAL</span><h2>Visibilidade total da planta,<br/>decisões mais rápidas.</h2><p>Fluidos, granéis, logística, manutenção e segurança em uma única experiência operacional.</p></div></section><section className="metrics">{metrics.map(([l,v,I]:any)=><article key={l}><div><I/></div><span>{l}</span><strong>{v}</strong><small>Atualizado agora</small></article>)}</section><section className="tank-grid-list">{tanks.slice(0,8).map(t=><TankCard key={t.id} tank={t} onOpen={setSelected}/>)}</section></>}
 {active==='Painel TV'&&<TVPanel tanks={tanks} operations={operations} vessels={vessels} trucks={trucks} qhse={qhse} alerts={alerts} summary={summary}/>}
 {active==='Tanques e silos'&&<TanksPanel tanks={filtered} query={query} onQuery={setQuery} renderTank={t=><TankCard key={t.id} tank={t} onOpen={setSelected}/>}/>} 
 {active==='Operações'&&<OperationsPanel operations={operations} canEdit={writeOps} onNew={()=>openOperation()} onEdit={openOperation}/>} 
 {active==='Embarcações'&&<VesselsPanel vessels={vessels}/>} 
 {active==='Carretas'&&<TrucksPanel trucks={trucks} canEdit={writeTrucks} saving={saving} onNew={()=>setFormOpen('truck')} onAdvance={moveTruck}/>} 
 {active==='Manutenção'&&<MaintenancePanel maintenance={maintenance} canCreate={writeMaintenance} onCreate={()=>setFormOpen('maintenance')}/>} 
 {active==='QHSE'&&<QhsePanel records={qhse} canCreate={writeQhse} onCreate={()=>setFormOpen('qhse')}/>} 
 {active==='Auditoria'&&<AuditPanel entries={audit}/>} 
 </main>
 <Dialog open={alertsOpen} onClose={setAlertsOpen} className="dialog"><div className="dialog-backdrop"/><DialogPanel className="dialog-panel"><div className="dialog-title"><DialogTitle>Central de alertas</DialogTitle><button onClick={()=>setAlertsOpen(false)}><X/></button></div>{alerts.map((a:any)=><div className="alert" key={a.alert_key||a.title}><i/><div><strong>{a.title}</strong><span>{a.message}</span></div></div>)}</DialogPanel></Dialog>
 <Dialog open={Boolean(selected)} onClose={()=>setSelected(null)} className="dialog"><div className="dialog-backdrop"/><DialogPanel className="dialog-panel tank-detail">{selected&&<><div className="dialog-title"><DialogTitle>{selected.name}</DialogTitle><button onClick={()=>setSelected(null)}><X/></button></div><div className="detail-summary"><span>{selected.kind} · {selected.phase}</span><h3>{selected.current_product||'Sem produto'}</h3><strong>{selected.current_volume} / {selected.capacity} {selected.unit}</strong><p>Cliente: {selected.client||'—'} · Lote: {selected.current_lot||'—'}</p>{writeTanks&&<button className="primary" onClick={()=>setEditOpen(true)}>Atualizar tanque</button>}</div><h4>Histórico recente</h4><div className="history-list">{history.map(h=><article key={h.id}><i/><div><strong>{h.movement_type||'Atualização'}</strong><span>{new Date(h.created_at).toLocaleString('pt-BR')}</span><small>{h.notes||`${h.previous_volume??'-'} → ${h.new_volume??'-'}`}</small></div></article>)}</div></>}</DialogPanel></Dialog>
 <Dialog open={editOpen} onClose={setEditOpen} className="dialog"><div className="dialog-backdrop"/><DialogPanel className="dialog-panel form-panel"><div className="dialog-title"><DialogTitle>Atualizar {selected?.name}</DialogTitle><button onClick={()=>setEditOpen(false)}><X/></button></div><label>Volume<input type="number" value={tankForm.volume} onChange={e=>setTankForm({...tankForm,volume:Number(e.target.value)})}/></label><label>Status<select value={tankForm.status} onChange={e=>setTankForm({...tankForm,status:e.target.value})}><option>Disponível</option><option>Operando</option><option>Recebendo</option><option>Bloqueado</option><option>Manutenção</option></select></label><label>Produto<select value={tankForm.fluid_type_id} onChange={e=>setTankForm({...tankForm,fluid_type_id:e.target.value})}><option value="">Selecione</option>{fluids.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Cliente<input value={tankForm.client} onChange={e=>setTankForm({...tankForm,client:e.target.value})}/></label><label>Lote<input value={tankForm.lot} onChange={e=>setTankForm({...tankForm,lot:e.target.value})}/></label><button className="primary" disabled={saving||!tankForm.fluid_type_id} onClick={saveTank}><Save size={17}/>{saving?'Salvando...':'Salvar atualização'}</button></DialogPanel></Dialog>
 <Dialog open={formOpen==='operation'} onClose={()=>setFormOpen(null)} className="dialog"><div className="dialog-backdrop"/><DialogPanel className="dialog-panel form-panel"><div className="dialog-title"><DialogTitle>{editOperation?'Editar operação':'Nova operação'}</DialogTitle><button onClick={()=>setFormOpen(null)}><X/></button></div><label>Embarcação<input value={operationForm.vessel} onChange={e=>setOperationForm({...operationForm,vessel:e.target.value})}/></label><label>Cliente<input value={operationForm.client} onChange={e=>setOperationForm({...operationForm,client:e.target.value})}/></label><label>Produto<input value={operationForm.product} onChange={e=>setOperationForm({...operationForm,product:e.target.value})}/></label><label>Atividade<input value={operationForm.activity} onChange={e=>setOperationForm({...operationForm,activity:e.target.value})}/></label><label>Planejado<input type="number" value={operationForm.planned_quantity} onChange={e=>setOperationForm({...operationForm,planned_quantity:Number(e.target.value)})}/></label>{editOperation&&<><label>Executado<input type="number" value={operationForm.executed_quantity} onChange={e=>setOperationForm({...operationForm,executed_quantity:Number(e.target.value)})}/></label><label>Status<select value={operationForm.status} onChange={e=>setOperationForm({...operationForm,status:e.target.value})}><option>Programada</option><option>Em andamento</option><option>Pausada</option><option>Concluída</option><option>Cancelada</option></select></label></>}<label>Unidade<input value={operationForm.unit} onChange={e=>setOperationForm({...operationForm,unit:e.target.value})}/></label><label>Programada para<input type="datetime-local" value={operationForm.scheduled_at} onChange={e=>setOperationForm({...operationForm,scheduled_at:e.target.value})}/></label><label>Observações<textarea value={operationForm.notes} onChange={e=>setOperationForm({...operationForm,notes:e.target.value})}/></label><button className="primary" disabled={saving} onClick={saveOperation}><Save size={17}/>{saving?'Salvando...':'Salvar operação'}</button></DialogPanel></Dialog>
 <Dialog open={formOpen==='truck'} onClose={()=>setFormOpen(null)} className="dialog"><div className="dialog-backdrop"/><DialogPanel className="dialog-panel form-panel"><div className="dialog-title"><DialogTitle>Nova carreta</DialogTitle><button onClick={()=>setFormOpen(null)}><X/></button></div><label>Data<input type="date" value={truckForm.movement_date} onChange={e=>setTruckForm({...truckForm,movement_date:e.target.value})}/></label><label>Tipo de movimentação<select value={truckForm.movement_type} onChange={e=>setTruckForm({...truckForm,movement_type:e.target.value})}><option>Entrada</option><option>Saída</option></select></label><label>Fornecedor<input value={truckForm.supplier} onChange={e=>setTruckForm({...truckForm,supplier:e.target.value})}/></label><label>Cliente<input value={truckForm.client} onChange={e=>setTruckForm({...truckForm,client:e.target.value})}/></label><label>Produto<input value={truckForm.product} onChange={e=>setTruckForm({...truckForm,product:e.target.value})}/></label><label>Quantidade<input type="number" value={truckForm.quantity} onChange={e=>setTruckForm({...truckForm,quantity:Number(e.target.value)})}/></label><label>Unidade<input value={truckForm.unit} onChange={e=>setTruckForm({...truckForm,unit:e.target.value})}/></label><label>Placa<input value={truckForm.plate} onChange={e=>setTruckForm({...truckForm,plate:e.target.value})}/></label><label>Motorista<input value={truckForm.driver_name} onChange={e=>setTruckForm({...truckForm,driver_name:e.target.value})}/></label><label>Nota fiscal<input value={truckForm.invoice_number} onChange={e=>setTruckForm({...truckForm,invoice_number:e.target.value})}/></label><button className="primary" disabled={saving} onClick={()=>act(()=>createTruck(truckForm),'Carreta cadastrada com sucesso.')}><Save size={17}/>Salvar carreta</button></DialogPanel></Dialog>
 <Dialog open={formOpen==='maintenance'} onClose={()=>setFormOpen(null)} className="dialog"><div className="dialog-backdrop"/><DialogPanel className="dialog-panel form-panel"><div className="dialog-title"><DialogTitle>Nova ordem de manutenção</DialogTitle><button onClick={()=>setFormOpen(null)}><X/></button></div><label>Equipamento<select value={maintenanceForm.equipment_id} onChange={e=>setMaintenanceForm({...maintenanceForm,equipment_id:e.target.value})}><option value="">Selecione</option>{equipment.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Título<input value={maintenanceForm.title} onChange={e=>setMaintenanceForm({...maintenanceForm,title:e.target.value})}/></label><label>Descrição<textarea value={maintenanceForm.description} onChange={e=>setMaintenanceForm({...maintenanceForm,description:e.target.value})}/></label><label>Prioridade<select value={maintenanceForm.priority} onChange={e=>setMaintenanceForm({...maintenanceForm,priority:e.target.value})}><option>Baixa</option><option>Média</option><option>Alta</option><option>Crítica</option></select></label><label>Tipo<select value={maintenanceForm.maintenance_type} onChange={e=>setMaintenanceForm({...maintenanceForm,maintenance_type:e.target.value})}><option>Corretiva</option><option>Preventiva</option><option>Inspeção</option></select></label><label>Responsável<input value={maintenanceForm.responsible} onChange={e=>setMaintenanceForm({...maintenanceForm,responsible:e.target.value})}/></label><label>Prazo<input type="date" value={maintenanceForm.due_date} onChange={e=>setMaintenanceForm({...maintenanceForm,due_date:e.target.value})}/></label><button className="primary" disabled={saving||!maintenanceForm.equipment_id} onClick={()=>act(()=>createMaintenance(maintenanceForm),'Ordem de manutenção criada.')}><Save size={17}/>Salvar ordem</button></DialogPanel></Dialog>
 <Dialog open={formOpen==='qhse'} onClose={()=>setFormOpen(null)} className="dialog"><div className="dialog-backdrop"/><DialogPanel className="dialog-panel form-panel"><div className="dialog-title"><DialogTitle>Novo registro QHSE</DialogTitle><button onClick={()=>setFormOpen(null)}><X/></button></div><label>Data<input type="date" value={qhseForm.record_date} onChange={e=>setQhseForm({...qhseForm,record_date:e.target.value})}/></label><label>Tipo<select value={qhseForm.record_type} onChange={e=>setQhseForm({...qhseForm,record_type:e.target.value})}><option>Observação</option><option>Inspeção</option><option>Desvio</option><option>Incidente</option><option>DDS</option></select></label><label>Título<input value={qhseForm.title} onChange={e=>setQhseForm({...qhseForm,title:e.target.value})}/></label><label>Descrição<textarea value={qhseForm.description} onChange={e=>setQhseForm({...qhseForm,description:e.target.value})}/></label><label>Responsável<input value={qhseForm.responsible} onChange={e=>setQhseForm({...qhseForm,responsible:e.target.value})}/></label><label>Severidade<select value={qhseForm.severity} onChange={e=>setQhseForm({...qhseForm,severity:e.target.value})}><option>Baixa</option><option>Média</option><option>Alta</option><option>Crítica</option></select></label><button className="primary" disabled={saving} onClick={()=>act(()=>createQhse(qhseForm),'Registro QHSE criado.')}><Save size={17}/>Salvar registro</button></DialogPanel></Dialog>
 </div>
}

export default function App(){const[session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(Boolean(supabase)),[demo,setDemo]=useState(false);useEffect(()=>{if(!supabase){setChecking(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)});const{data}=supabase.auth.onAuthStateChange((_e,next)=>setSession(next));return()=>data.subscription.unsubscribe()},[]);if(checking)return <div className="boot-screen"><div className="brand-mark">OC</div><strong>Inicializando OPSControl IA Next</strong></div>;if(!session&&!demo)return <Login onDemo={()=>setDemo(true)}/>;return <Dashboard demo={demo} onExitDemo={()=>setDemo(false)}/>}
