import {Dialog,DialogPanel,DialogTitle} from '@headlessui/react';
import {motion} from 'motion/react';
import {Activity,Bell,Boxes,CheckCircle2,ChevronRight,Droplets,Gauge,LogOut,Menu,Monitor,Save,Search,ShieldCheck,Ship,Truck,Wrench,X} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {Login} from './components/Login';
import {advanceTruck,canWrite,createOperation,loadDashboard,loadFluidTypes,loadProfile,loadTankHistory,updateTank,type FluidType,type Maintenance,type Operation,type Profile,type QhseRecord,type Tank,type TankHistory,type Truck,type VesselSchedule} from './lib/data';
import {supabase} from './lib/supabase';

const nav=[['Visão geral',Gauge],['Painel TV',Monitor],['Operações',Activity],['Tanques e silos',Droplets],['Embarcações',Ship],['Carretas',Truck],['Manutenção',Wrench],['QHSE',ShieldCheck]] as const;
const demoTanks:Tank[]=[{id:'1',name:'TK-04',kind:'WBM',phase:'Phase #1',capacity:1000,current_volume:760,current_product:'KCL Polymer 9.8 ppg',status:'Operando',unit:'bbl',client:'Equinor',current_lot:'L-2407'}];

function TankCard({tank,onOpen}:{tank:Tank;onOpen:(tank:Tank)=>void}){const pct=Math.min(100,Math.round(tank.current_volume/(tank.capacity||1)*100));return <motion.article whileHover={{y:-4}} className="tank-card"><div className="card-top"><div><span>{tank.kind}</span><h3>{tank.name}</h3></div><b>{tank.status}</b></div><div className="tank-visual"><motion.div className="liquid" animate={{height:`${pct}%`}}/><div className="tank-grid"/><strong>{pct}%</strong></div><div className="tank-copy"><h4>{tank.current_product||'Sem produto'}</h4><p>{tank.current_volume.toLocaleString('pt-BR')} / {tank.capacity.toLocaleString('pt-BR')} {tank.unit}</p><small>{tank.client||'Sem cliente'} · {tank.phase}</small></div><button onClick={()=>onOpen(tank)}>Ver detalhes <ChevronRight size={16}/></button></motion.article>}

function Dashboard({demo,onExitDemo}:{demo:boolean;onExitDemo:()=>void}){
 const[active,setActive]=useState('Visão geral'),[sidebar,setSidebar]=useState(false),[alertsOpen,setAlertsOpen]=useState(false),[selected,setSelected]=useState<Tank|null>(null),[editOpen,setEditOpen]=useState(false),[newOperation,setNewOperation]=useState(false);
 const[tanks,setTanks]=useState<Tank[]>(demo?demoTanks:[]),[operations,setOperations]=useState<Operation[]>([]),[vessels,setVessels]=useState<VesselSchedule[]>([]),[trucks,setTrucks]=useState<Truck[]>([]),[maintenance,setMaintenance]=useState<Maintenance[]>([]),[qhse,setQhse]=useState<QhseRecord[]>([]),[alerts,setAlerts]=useState<any[]>([]),[summary,setSummary]=useState<any>(null),[history,setHistory]=useState<TankHistory[]>([]),[profile,setProfile]=useState<Profile|null>(null),[fluids,setFluids]=useState<FluidType[]>([]),[notice,setNotice]=useState('');
 const[query,setQuery]=useState(''),[saving,setSaving]=useState(false);
 const[tankForm,setTankForm]=useState({volume:0,status:'Disponível',client:'',lot:'',fluid_type_id:''});
 const[operationForm,setOperationForm]=useState({vessel:'',client:'',product:'',activity:'Bombeio',planned_quantity:0,unit:'bbl',scheduled_at:''});
 async function refresh(){if(demo)return;const d=await loadDashboard();setTanks(d.tanks);setOperations(d.operations);setVessels(d.vessels);setTrucks(d.trucks);setMaintenance(d.maintenance);setQhse(d.qhse);setAlerts(d.alerts);setSummary(d.summary)}
 useEffect(()=>{if(demo)return;Promise.all([refresh(),loadProfile().then(setProfile),loadFluidTypes().then(setFluids)]).catch(e=>setNotice(e.message))},[demo]);
 useEffect(()=>{if(!selected)return;loadTankHistory(selected.id).then(setHistory).catch(()=>setHistory([]));setTankForm({volume:selected.current_volume,status:selected.status,client:selected.client||'',lot:selected.current_lot||'',fluid_type_id:selected.current_fluid_type_id||''})},[selected]);
 const filtered=useMemo(()=>tanks.filter(t=>`${t.name} ${t.current_product||''} ${t.client||''}`.toLowerCase().includes(query.toLowerCase())),[tanks,query]);
 const total=useMemo(()=>tanks.reduce((a,t)=>a+t.current_volume,0),[tanks]);
 const writeTanks=!demo&&canWrite(profile,'tanks'),writeOps=!demo&&canWrite(profile,'operations'),writeTrucks=!demo&&canWrite(profile,'trucks');
 async function logout(){if(demo)onExitDemo();else await supabase?.auth.signOut()}
 async function saveTank(){if(!selected)return;setSaving(true);setNotice('');try{await updateTank(selected,tankForm);await refresh();setEditOpen(false);setSelected(null);setNotice('Tanque atualizado com sucesso.')}catch(e:any){setNotice(e.message||'Falha ao atualizar tanque.')}finally{setSaving(false)}}
 async function saveOperation(){setSaving(true);setNotice('');try{await createOperation(operationForm);await refresh();setNewOperation(false);setNotice('Operação criada com sucesso.')}catch(e:any){setNotice(e.message||'Falha ao criar operação.')}finally{setSaving(false)}}
 async function moveTruck(id:string,current:string|null){const stages=['programada','portaria','pátio','operação','liberada'];const next=stages[Math.min(stages.length-1,Math.max(0,stages.indexOf((current||'programada').toLowerCase())+1))];setSaving(true);try{await advanceTruck(id,next);await refresh();setNotice(`Carreta avançada para ${next}.`)}catch(e:any){setNotice(e.message||'Falha ao avançar carreta.')}finally{setSaving(false)}}
 const head=(eyebrow:string,title:string,text:string,action?:React.ReactNode)=><div className="module-head"><div><span>{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>{action}</div>;
 const metrics=[['Volume monitorado',`${total.toLocaleString('pt-BR')} un.`,Droplets],['Operações ativas',String(summary?.operations_in_progress??operations.length),Activity],['Carretas pendentes',String(summary?.trucks_pending??trucks.length),Truck],['Pendências QHSE',String(summary?.qhse_pending??qhse.filter(q=>q.status!=='Concluído').length),ShieldCheck]];
 return <div className="app-shell"><aside className={`sidebar ${sidebar?'open':''}`}><div className="brand"><div className="brand-mark"><Boxes/></div><div><strong>OPSControl</strong><span>IA NEXT</span></div><button onClick={()=>setSidebar(false)}><X/></button></div><div className="plant"><i/><div><span>{demo?'MODO HOMOLOGAÇÃO':'PLANTA ATIVA'}</span><strong>B-PORT LMP</strong></div></div><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?'active':''} onClick={()=>{setActive(label);setSidebar(false)}}><Icon size={18}/>{label}</button>)}</nav><button className="logout" onClick={logout}><LogOut size={18}/>Sair</button><div className="user"><div>{profile?.full_name?.slice(0,2).toUpperCase()||'OC'}</div><span><strong>{profile?.full_name||'Homologação visual'}</strong><small>{profile?.role||'Dados demonstrativos'}</small></span></div></aside>
 <main><header><button className="menu" onClick={()=>setSidebar(true)}><Menu/></button><div><span>Centro de controle operacional</span><h1>{active}</h1></div><button className="icon-button" onClick={()=>setAlertsOpen(true)}><Bell/><i>{alerts.length}</i></button></header>{notice&&<div className="notice"><CheckCircle2 size={18}/>{notice}<button onClick={()=>setNotice('')}><X size={15}/></button></div>}
 {active==='Visão geral'&&<><section className="hero"><div><span className="eyebrow">OPERAÇÃO EM TEMPO REAL</span><h2>Visibilidade total da planta,<br/>decisões mais rápidas.</h2><p>Fluidos, granéis, logística, manutenção e segurança em uma única experiência operacional.</p></div></section><section className="metrics">{metrics.map(([l,v,I]:any)=><article key={l}><div><I/></div><span>{l}</span><strong>{v}</strong><small>Atualizado agora</small></article>)}</section><section className="tank-grid-list">{tanks.slice(0,8).map(t=><TankCard key={t.id} tank={t} onOpen={setSelected}/>)}</section></>}
 {active==='Painel TV'&&<section className="tv-page">{head('CENTRO DE CONTROLE','Painel TV','Leitura executiva para acompanhamento contínuo.')}<div className="tv-metrics">{metrics.map(([l,v,I]:any)=><article key={l}><I/><span>{l}</span><strong>{v}</strong></article>)}</div></section>}
 {active==='Tanques e silos'&&<section>{head('GESTÃO DE TANCAGEM','Tanques e silos','Capacidade, produto, cliente, status e histórico.')}<div className="filters"><div><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar tanque, produto ou cliente"/></div></div><div className="tank-grid-list expanded">{filtered.map(t=><TankCard key={t.id} tank={t} onOpen={setSelected}/>)}</div></section>}
 {active==='Operações'&&<section>{head('PROGRAMAÇÃO OPERACIONAL','Operações','Planejado versus executado.',writeOps&&<button className="primary" onClick={()=>setNewOperation(true)}>Nova operação</button>)}<div className="data-list">{operations.map(o=><article key={o.id}><div><strong>{o.vessel}</strong><span>{o.client} · {o.product}</span></div><b>{o.executed_quantity}/{o.planned_quantity} {o.unit}</b><small>{o.status}</small></article>)}</div></section>}
 {active==='Embarcações'&&<section>{head('CRONOGRAMA MARÍTIMO','Embarcações','ETA, cliente, produto e berço.')}<div className="vessel-grid">{vessels.map(v=><article key={v.id}><Ship/><div><strong>{v.vessel_name}</strong><span>{v.client} · {v.product||v.operation_type}</span></div><b>{v.status}</b></article>)}</div></section>}
 {active==='Carretas'&&<section>{head('FLUXO LOGÍSTICO','Carretas','Entrada, operação e liberação.')}<div className="workflow-grid">{trucks.map(t=><article key={t.id}><Truck/><div><strong>{t.plate||'Sem placa'}</strong><span>{t.product} · {t.quantity} {t.unit}</span><small>{t.supplier} · NF {t.invoice_number||'—'}</small></div><div><b>{t.workflow_stage}</b>{writeTrucks&&<button className="mini-action" disabled={saving} onClick={()=>moveTruck(t.id,t.workflow_stage)}>Avançar etapa</button>}</div></article>)}</div></section>}
 {active==='Manutenção'&&<section>{head('CONFIABILIDADE','Manutenção','Ordens, prioridades e prazos.')}<div className="cards-list">{maintenance.map(m=><article key={m.id}><Wrench/><div><strong>{m.title}</strong><span>{m.equipment?.name||'Equipamento'} · {m.maintenance_type}</span></div><b>{m.status}</b></article>)}</div></section>}
 {active==='QHSE'&&<section>{head('SEGURANÇA E CONFORMIDADE','QHSE','Registros e tratamento de pendências.')}<div className="cards-list">{qhse.map(q=><article key={q.id}><ShieldCheck/><div><strong>{q.title}</strong><span>{q.record_type} · {q.severity}</span></div><b>{q.status}</b></article>)}</div></section>}
 </main>
 <Dialog open={alertsOpen} onClose={setAlertsOpen} className="dialog"><div className="dialog-backdrop"/><DialogPanel className="dialog-panel"><div className="dialog-title"><DialogTitle>Central de alertas</DialogTitle><button onClick={()=>setAlertsOpen(false)}><X/></button></div>{alerts.map((a:any)=><div className="alert" key={a.alert_key||a.title}><i/><div><strong>{a.title}</strong><span>{a.message}</span></div></div>)}</DialogPanel></Dialog>
 <Dialog open={Boolean(selected)} onClose={()=>setSelected(null)} className="dialog"><div className="dialog-backdrop"/><DialogPanel className="dialog-panel tank-detail">{selected&&<><div className="dialog-title"><DialogTitle>{selected.name}</DialogTitle><button onClick={()=>setSelected(null)}><X/></button></div><div className="detail-summary"><span>{selected.kind} · {selected.phase}</span><h3>{selected.current_product||'Sem produto'}</h3><strong>{selected.current_volume} / {selected.capacity} {selected.unit}</strong><p>Cliente: {selected.client||'—'} · Lote: {selected.current_lot||'—'}</p>{writeTanks&&<button className="primary" onClick={()=>setEditOpen(true)}>Atualizar tanque</button>}</div><h4>Histórico recente</h4><div className="history-list">{history.map(h=><article key={h.id}><i/><div><strong>{h.movement_type||'Atualização'}</strong><span>{new Date(h.created_at).toLocaleString('pt-BR')}</span><small>{h.notes||`${h.previous_volume??'-'} → ${h.new_volume??'-'}`}</small></div></article>)}</div></>}</DialogPanel></Dialog>
 <Dialog open={editOpen} onClose={setEditOpen} className="dialog"><div className="dialog-backdrop"/><DialogPanel className="dialog-panel form-panel"><div className="dialog-title"><DialogTitle>Atualizar {selected?.name}</DialogTitle><button onClick={()=>setEditOpen(false)}><X/></button></div><label>Volume<input type="number" value={tankForm.volume} onChange={e=>setTankForm({...tankForm,volume:Number(e.target.value)})}/></label><label>Status<select value={tankForm.status} onChange={e=>setTankForm({...tankForm,status:e.target.value})}><option>Disponível</option><option>Operando</option><option>Recebendo</option><option>Bloqueado</option><option>Manutenção</option></select></label><label>Produto<select value={tankForm.fluid_type_id} onChange={e=>setTankForm({...tankForm,fluid_type_id:e.target.value})}><option value="">Selecione</option>{fluids.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Cliente<input value={tankForm.client} onChange={e=>setTankForm({...tankForm,client:e.target.value})}/></label><label>Lote<input value={tankForm.lot} onChange={e=>setTankForm({...tankForm,lot:e.target.value})}/></label><button className="primary" disabled={saving||!tankForm.fluid_type_id} onClick={saveTank}><Save size={17}/>{saving?'Salvando...':'Salvar atualização'}</button></DialogPanel></Dialog>
 <Dialog open={newOperation} onClose={setNewOperation} className="dialog"><div className="dialog-backdrop"/><DialogPanel className="dialog-panel form-panel"><div className="dialog-title"><DialogTitle>Nova operação</DialogTitle><button onClick={()=>setNewOperation(false)}><X/></button></div>{(['vessel','client','product','activity','unit','scheduled_at'] as const).map(k=><label key={k}>{k}<input type={k==='scheduled_at'?'datetime-local':'text'} value={operationForm[k]} onChange={e=>setOperationForm({...operationForm,[k]:e.target.value})}/></label>)}<label>Quantidade planejada<input type="number" value={operationForm.planned_quantity} onChange={e=>setOperationForm({...operationForm,planned_quantity:Number(e.target.value)})}/></label><button className="primary" disabled={saving} onClick={saveOperation}><Save size={17}/>{saving?'Salvando...':'Criar operação'}</button></DialogPanel></Dialog>
 </div>
}

export default function App(){const[session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(Boolean(supabase)),[demo,setDemo]=useState(false);useEffect(()=>{if(!supabase){setChecking(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)});const{data}=supabase.auth.onAuthStateChange((_e,next)=>setSession(next));return()=>data.subscription.unsubscribe()},[]);if(checking)return <div className="boot-screen"><div className="brand-mark">OC</div><strong>Inicializando OPSControl IA Next</strong></div>;if(!session&&!demo)return <Login onDemo={()=>setDemo(true)}/>;return <Dashboard demo={demo} onExitDemo={()=>setDemo(false)}/>}
